/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restaurante;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Administrador
 */
public class RestauranteComidaRapida extends javax.swing.JFrame {

    /**
     * Creates new form RestauranteComidaRapida
     */
    public RestauranteComidaRapida() {
        initComponents();
         setLocationRelativeTo(null);//centra la ventana en la patalla
        setTitle("Resturante");
        setVisible(true);
        
    }
    
    public void rellenarTabla(){
      PreciosTable.getValueAt(2, 1);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        SopaLabel = new javax.swing.JLabel();
        PostreLabel = new javax.swing.JLabel();
        HamburguesaSpinner = new javax.swing.JSpinner();
        AceptarButton = new javax.swing.JButton();
        CervezaSpinner = new javax.swing.JSpinner();
        LimpiarButton = new javax.swing.JButton();
        GaseosaSpinner = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        EnsaladaSpinner = new javax.swing.JSpinner();
        RefrescoSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        PreciosTable = new javax.swing.JTable();
        HamburguesaLabel = new javax.swing.JLabel();
        CervezaLabel = new javax.swing.JLabel();
        SalchichasSpinner = new javax.swing.JSpinner();
        SopaSpinner = new javax.swing.JSpinner();
        PostreSpinner = new javax.swing.JSpinner();
        VentasLabel = new javax.swing.JLabel();
        GaseosaLabel = new javax.swing.JLabel();
        ImpuestosLabel = new javax.swing.JLabel();
        EnsaladaLabel = new javax.swing.JLabel();
        VentasTotalesTextField = new javax.swing.JTextField();
        SalchichasLabel = new javax.swing.JLabel();
        ImpuestosTotalesTextField = new javax.swing.JTextField();
        RefrescoLabel = new javax.swing.JLabel();
        ModoOscuroCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SopaLabel.setText("Sopa");

        PostreLabel.setText("Postre");

        HamburguesaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        HamburguesaSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        CervezaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CervezaSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        LimpiarButton.setText("Limpiar");
        LimpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarButtonActionPerformed(evt);
            }
        });

        GaseosaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        GaseosaSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurante/32437.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.setPreferredSize(new java.awt.Dimension(72, 22));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        EnsaladaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        EnsaladaSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        RefrescoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        RefrescoSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        PreciosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hamburguesa",  new Double(2.5)},
                {"Cerveza",  new Double(4.0)},
                {"Gaseosa",  new Double(3.0)},
                {"Ensalada",  new Double(1.5)},
                {"Salchichas",  new Double(2.0)},
                {"Refresco",  new Double(1.0)},
                {"Sopa",  new Double(1.5)},
                {"Postre",  new Double(1.5)}
            },
            new String [] {
                "Menú", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PreciosTable.setToolTipText("");
        PreciosTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(PreciosTable);
        if (PreciosTable.getColumnModel().getColumnCount() > 0) {
            PreciosTable.getColumnModel().getColumn(0).setResizable(false);
            PreciosTable.getColumnModel().getColumn(1).setResizable(false);
        }

        HamburguesaLabel.setText("Hamburguesa");

        CervezaLabel.setText("Cerveza");

        SalchichasSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SalchichasSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        SopaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SopaSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        PostreSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        PostreSpinner.setPreferredSize(new java.awt.Dimension(80, 22));

        VentasLabel.setText("Ventas totales");

        GaseosaLabel.setText("Gaseosa");

        ImpuestosLabel.setText("Impuestos");

        EnsaladaLabel.setText("Ensalada");

        VentasTotalesTextField.setEditable(false);
        VentasTotalesTextField.setMinimumSize(new java.awt.Dimension(284, 22));
        VentasTotalesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasTotalesTextFieldActionPerformed(evt);
            }
        });

        SalchichasLabel.setText("Salchichas");

        ImpuestosTotalesTextField.setEditable(false);
        ImpuestosTotalesTextField.setMinimumSize(new java.awt.Dimension(284, 22));

        RefrescoLabel.setText("Refresco");

        ModoOscuroCheckBox.setText("Modo oscuro");
        ModoOscuroCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModoOscuroCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnsaladaLabel)
                            .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FondoLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SopaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PostreLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(RefrescoLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(SalchichasLabel)))
                        .addGap(27, 27, 27)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnsaladaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RefrescoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalchichasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SopaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HamburguesaLabel)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GaseosaLabel)
                                    .addComponent(CervezaLabel))
                                .addGap(3, 3, 3)))
                        .addGap(27, 27, 27)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CervezaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GaseosaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HamburguesaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                        .addComponent(VentasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(VentasTotalesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(ImpuestosLabel)
                        .addGap(36, 36, 36)
                        .addComponent(ImpuestosTotalesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModoOscuroCheckBox)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(AceptarButton))
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addComponent(LimpiarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AceptarButton)
                        .addGap(33, 33, 33)
                        .addComponent(LimpiarButton)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModoOscuroCheckBox))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HamburguesaLabel)
                                    .addComponent(HamburguesaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CervezaLabel)
                                    .addComponent(CervezaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GaseosaLabel)
                                    .addComponent(GaseosaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FondoLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(SalchichasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FondoLayout.createSequentialGroup()
                                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EnsaladaLabel)
                                            .addComponent(EnsaladaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SalchichasLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RefrescoLabel)
                                            .addComponent(RefrescoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SopaLabel)
                                            .addComponent(SopaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(PostreLabel)
                                            .addComponent(PostreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(VentasLabel)
                                    .addComponent(VentasTotalesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 15, Short.MAX_VALUE)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImpuestosTotalesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImpuestosLabel))))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //cambia los colores
    private void ModoOscuroCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModoOscuroCheckBoxActionPerformed
       Fondo.setBackground(Color.BLACK);
       HamburguesaLabel.setForeground(Color.white);
       CervezaLabel.setForeground(Color.white);
       GaseosaLabel.setForeground(Color.white);
       EnsaladaLabel.setForeground(Color.white);
       SalchichasLabel.setForeground(Color.white);
       RefrescoLabel.setForeground(Color.white);
       SopaLabel.setForeground(Color.white);
       PostreLabel.setForeground(Color.white);
       VentasLabel.setForeground(Color.white);
       ImpuestosLabel.setForeground(Color.white);
       ModoOscuroCheckBox.setForeground(Color.white);

       if(!ModoOscuroCheckBox.isSelected()){
           Fondo.setBackground(Color.white);
           HamburguesaLabel.setForeground(Color.BLACK);
            CervezaLabel.setForeground(Color.BLACK);
            GaseosaLabel.setForeground(Color.BLACK);
            EnsaladaLabel.setForeground(Color.BLACK);
            SalchichasLabel.setForeground(Color.BLACK);
            RefrescoLabel.setForeground(Color.BLACK);
            SopaLabel.setForeground(Color.BLACK);
            PostreLabel.setForeground(Color.BLACK);
            VentasLabel.setForeground(Color.BLACK);
            ImpuestosLabel.setForeground(Color.BLACK);
             ModoOscuroCheckBox.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_ModoOscuroCheckBoxActionPerformed

    private void VentasTotalesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasTotalesTextFieldActionPerformed

    }//GEN-LAST:event_VentasTotalesTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
    //limpia las casillas a valor default
    private void LimpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarButtonActionPerformed
        VentasTotalesTextField.setText(" ");
        ImpuestosTotalesTextField.setText(" ");
        HamburguesaSpinner.setValue(0);
        CervezaSpinner.setValue(0);
        GaseosaSpinner.setValue(0);
        EnsaladaSpinner.setValue(0);
        RefrescoSpinner.setValue(0);
        SalchichasSpinner.setValue(0);
        SopaSpinner.setValue(0);
        PostreSpinner.setValue(0);

    }//GEN-LAST:event_LimpiarButtonActionPerformed
    //cambia el texto de los label al ejecutar los metodos
    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        VentasTotalesTextField.setText( CalcularPrecioTotal());
        ImpuestosTotalesTextField.setText(CalcularImpuestos());
    }//GEN-LAST:event_AceptarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestauranteComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestauranteComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestauranteComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestauranteComidaRapida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestauranteComidaRapida().setVisible(true);
            }
        });
    }
    
    /**
    * Calcula el precio total de un producto en una fila específica de la tabla de precios,
    * multiplicando el precio unitario por la cantidad proporcionada.
    *
    * @param numFila   Índice de la fila en la tabla de precios.
    * @param cantidad  Cantidad del producto.
    * @return El precio total del producto.
    */
    public double FormulaCalcularPrecioTotal(int numFila, int cantidad) {
    // Obtener el precio unitario desde la tabla de precios
    double precioUni = (double) PreciosTable.getValueAt(numFila, 1);
    // Calcular y devolver el precio total
    return precioUni * cantidad;
}

    
    /**
     * Calcula el precio total de cada tipo de producto (Hamburguesa, Cerveza, Gaseosa, etc.)
     * multiplicando la cantidad por el precio unitario y luego suma todos los totales.
     *
     * @return El precio total de todos los productos.
     */
    public String CalcularPrecioTotal() {
    // Calcular el precio total de cada tipo de producto
    double Hamburguesatotal = FormulaCalcularPrecioTotal(0, (int) HamburguesaSpinner.getValue());
    double Cervezatotal = FormulaCalcularPrecioTotal(1, (int) CervezaSpinner.getValue());
    double Gaseosatotal = FormulaCalcularPrecioTotal(2, (int) GaseosaSpinner.getValue());
    double Ensaladatotal = FormulaCalcularPrecioTotal(3, (int) EnsaladaSpinner.getValue());
    double Salchichastotal = FormulaCalcularPrecioTotal(4, (int) SalchichasSpinner.getValue());
    double Refrescototal = FormulaCalcularPrecioTotal(5, (int) RefrescoSpinner.getValue());
    double Sopatotal = FormulaCalcularPrecioTotal(6, (int) SopaSpinner.getValue());
    double Postretotal = FormulaCalcularPrecioTotal(7, (int) PostreSpinner.getValue());

    // Calcular el total de todos los productos
    double calculoTotal = Hamburguesatotal + Cervezatotal + Gaseosatotal + Ensaladatotal + Salchichastotal + Refrescototal + Sopatotal + Postretotal;

    // Convertir el total a una cadena y devolverlo
    return String.valueOf(calculoTotal);
}

    
    /**
    * Calcula los impuestos aplicando una tasa fija del 7% al precio total de los productos.
    *
    * @return El monto de impuestos calculado.
    */
    public String CalcularImpuestos() {
    // Formatear números con dos decimales
    DecimalFormat df = new DecimalFormat("##.##");
    
    // Calcular el total de productos a partir del método CalcularPrecioTotal()
    double totalProductos = Double.parseDouble(CalcularPrecioTotal());
    
    // Calcular los impuestos aplicando una tasa del 7%
    double calculoImpuestos = totalProductos * 0.07;
    
    // Formatear el resultado y devolverlo como cadena
    return df.format(calculoImpuestos);
}
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JLabel CervezaLabel;
    private javax.swing.JSpinner CervezaSpinner;
    private javax.swing.JLabel EnsaladaLabel;
    private javax.swing.JSpinner EnsaladaSpinner;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel GaseosaLabel;
    private javax.swing.JSpinner GaseosaSpinner;
    private javax.swing.JLabel HamburguesaLabel;
    private javax.swing.JSpinner HamburguesaSpinner;
    private javax.swing.JLabel ImpuestosLabel;
    private javax.swing.JTextField ImpuestosTotalesTextField;
    private javax.swing.JButton LimpiarButton;
    private javax.swing.JCheckBox ModoOscuroCheckBox;
    private javax.swing.JLabel PostreLabel;
    private javax.swing.JSpinner PostreSpinner;
    private javax.swing.JTable PreciosTable;
    private javax.swing.JLabel RefrescoLabel;
    private javax.swing.JSpinner RefrescoSpinner;
    private javax.swing.JLabel SalchichasLabel;
    private javax.swing.JSpinner SalchichasSpinner;
    private javax.swing.JLabel SopaLabel;
    private javax.swing.JSpinner SopaSpinner;
    private javax.swing.JLabel VentasLabel;
    private javax.swing.JTextField VentasTotalesTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
